### ISSUE TITLE
What can I do with this setup?

### ISSUE THREAD

**Issue by NilsMinor** [bluerange-io/bluerange-setup#1]
Hi BlueRange Team,
I am very interested in your fruityMesh software. I found this setup and I want to know what I can use it for. My goal is to create connected garden lights based on custom hardware https://github.com/NilsMinor/inuk-base. 

Can I use this setup to create my own platform to control the overall communication or to track the communication on my mesh? Sorry for the rookie questions.

- Nils

**Comment by NilsMinor** [comment]
Sorry for my question, I found your documentation https://www.bluerange.io/docs/bluerange-installguide/abstract.html .

**Comment by mariusheil** [comment]
Hi, the problem with our platform will probably be that we are not currently open sourcing our Mesh gateway, so that part would need to be implemented by you. I think this is probably a bit of an over engineered solution for your project. But if you can use sth. that would be great of course.

**Comment by NilsMinor** [comment]
Could I use your bluerange USB Dongle as Mesh-Gateway? :)
